# -*- coding: utf-8 -*-
"""ELIAS ALONSO ZUNIGA OROZCO - Actividad 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cp5uUG-3uAglMYYD-5bhnHUFev5VdV_7

# **2.2 Sentencias Selectivas**

**Ejercicio 1**

Complete el código de la calculadora en extenso con las operaciones de multiplicación y división.
"""

#Ejemplo en extenso del menú de una calculadora sencilla

opc = input("¡Bienvenido a la calculadora!\n\nA. SUMA \nB. RESTA \nC. MULTIPLICACIÓN \nD. DIVISIÓN \n\nSeleccione una opción: ")#\n salto de línea

if opc == 'A' or opc == 'a': # Suma
  D1 = float(input("\nIngrese el primer número: "))
  D2 = float(input("Ingrese el segundo número: "))
  print("\nEl resultado de la suma es: {:.2f}".format(D1+D2))

elif opc == 'B' or opc == 'b': # Resta
  D1 = float(input("\nIngrese el primer número: "))
  D2 = float(input("Ingrese el segundo número: "))
  print("\nEl resultado de la resta es: {:.2f}".format(D1-D2))

# Completar las opciones para la multiplicación y la división

elif opc == 'C' or opc == 'c': # Multiplicacion
  D1 = float(input("\nIngrese el primer número: "))
  D2 = float(input("Ingrese el segundo número: "))
  print("\nEl resultado de la multiplicacion es: {:.2f}".format(D1*D2))

elif opc == 'D' or opc == 'd': # Division
  D1 = float(input("\nIngrese el primer número: "))
  D2 = float(input("Ingrese el segundo número: "))
  print("\nEl resultado de la division es: {:.2f}".format(D1/D2))


else:
  print("\nDato no válido")

"""**Ejercicio 2**

Complete el código de la calculadora sencilla o resumida con las operaciones de multiplicación y división.
"""

#Ejemplo resumido del menú de una calculadora sencilla

opc = input("¡Bienvenido a la calculadora! \n\nA. SUMA  \nB. RESTA \nC. MULTIPLICACIÓN \nD. DIVISIÓN \n\nSeleccione una opción:")#\n salto de línea
opc = opc.upper() # upper() Instrucción que transforma a mayúsculas lower() Instrucción que transforma a minúsculas
D1 = float(input("\nIngrese el primer número: "))
D2 = float(input("Ingrese el segundo número: "))

if opc == 'A': #Suma
  print("\nEl resultado de la suma es: {:.2f}".format(D1+D2))

elif opc == 'B': #Resta
  print("\nEl resultado de la resta es: {:.2f}".format(D1-D2))

# Completar las opciones para la multiplicación y la división

elif opc == 'C': #Multiplicacion
  print("\nEl resultado de la multiplicacion es: {:.2f}".format(D1*D2))

elif opc == 'B': #Division
  print("\nEl resultado de la division es: {:.2f}".format(D1/D2))

else:
  print("\nDato no válido")