# -*- coding: utf-8 -*-
"""ELIAS ALONSO ZUNIGA OROZCO - Copia de Actividad5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxgN6UThRYCSCBMHqpwkV48rDREeTupf

**Ejercicios para verificar los temas de expresiones y variables.**

Realice lo siguiente:

Escribir su nombre y su código en una celda de texto al inicio del documento de google colab.

**Ejercicio 1:**

Agregue una celda de código y en una variable guarde una cadena en la cual describa su motivación para estudiar la carrera de computación. Hecho esto realice lo siguiente:

*   Imprima en pantalla a la frase completa.
*   Duplique la frase por medio de una operación de repetición e imprima en pantalla.
*   Concatene la frase " Gracias por su atención. " al final de su frase e imprima en pantalla.

**Ejercicio 2:**

Declare dos variables (Ej. A = 14 y B = 50.98) con valores de tipo entero o real y realice lo siguiente:

*   Sume ambas variables e imprima el resultado.
*   Reste ambas variables e imprima el resultado.
*   Multiplique ambas variables e imprima el resultado.
*   Divida ambas variables e imprima el resultado.
*   Divida por medio de la división de piso a ambas variables e imprima el resultado.
*   Saque el módulo e imprima el resultado.
*   Eleve a ambas variables a la potencia 3 e imprima el resultado.

**Ejercicio 3:**

Tome las variables declaradas en el ejercicio 2, realice las siguientes comparaciones e imprima el resultado en pantalla:

*   Variable 1 igual a Variable 2
*   Variable 1 diferente a Variable 2
*   Variable 2 mayor que Variable 1
*   Variable 2 menor que Variable 1
*   Variable 1 mayor o igual que Variable 2
*   Variable 1 menor o igual que Variable 2

**Ejercicio 4:**

Tome las variables declaradas en el ejercicio 2 y realice lo siguiente e imprima el resultado en pantalla:



*   **no**(V1 - 5 >= V2 + 9 **y** V2 != V1)
*   (V2 x 5 < V1 / 3) **o** **no**(V1 == V2 potencia 2)

**Nota:** Separe cada ejercicio en una celda de código distinta y agregue una celda de texto que indique el nombre del ejercicio.
"""

#Ejercicio 1
cadena="joji god, vege god "
print (cadena)

print (cadena  * 2)

print (cadena, "Gracias por su atención.")

#Ejercicio 2
A = 8
B = 3.1416

print (A+B)
print (A-B)
print (A*B)
print (A/B)
print (A//B)
print (A%B)
print (A**3, B**3)

#Ejercicio 3
print (A==B)
print (A!=B)
print (A>B)
print (A<B)
print (A>=B)
print (A<=B)

#Ejercicio 4
print (not(A-5>=B+9 and B!=A))
print ((B*5<A/3) or not (A==B**2))