# -*- coding: utf-8 -*-
"""ELIAS ALONSO ZUNIGA OROZCO - Actividad 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAUcqcOuM3Zo_iU72iifiDFKYcBNP4zb

# **Sentencia for**

**Ejercicio 1**

> Solicite al usuario que ingrese una frase e imprima cuantas veces aparece cada vocal (a, e, i, o, u).

**Ejemplo de salida en pantalla:**

```
Ingresa una frase: Hola a todos

La letra a aparece 2 veces

La letra e aparece 0 veces

La letra i aparece 0 veces

La letra o aparece 3 veces

La letra u aparece 0 veces
```
"""

frase=input("Ingresa una frase: ")
A=0
E=0
I=0
O=0
U=0
for letra in frase:
  if letra=="a":
    A+=1
  if letra=="e":
    E+=1
  if letra=="i":
    I+=1
  if letra=="o":
    O+=1
  if letra=="u":
    U+=1
print("La letra a aparece",A,"veces")
print("La letra e aparece",E,"veces")
print("La letra i aparece",I,"veces")
print("La letra o aparece",O,"veces")
print("La letra u aparece",U,"veces")

"""**Ejercicio 2**

> Muestre en pantalla todos los números impares que se encuentran del 1 al 80.

**Ejemplo de salida en pantalla**

```
Los números impares del 1 al 80 son:

1
3
5
7
...
75
77
79
```




"""

print("Los numeros impares del 1 al 80 son:")
for a in range(1,80,2):
  print(a)

"""**Ejercicio 3**



> Realice un algoritmo para obtener la tabla de multiplicar de un número entero comenzando desde el 1 y terminando la tabla en 10.



```
Ingrese el número del cúal desea conocer su tabla de multiplicar: 5

La tabla de multiplicar del número 5 es:
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
```




"""

a=int(input("Ingrese el número del cúal desea conocer su tabla de multiplicar: "))
print("La tabla de multiplicar del número,",a,"es:")
b=0

for x in range(a,a*11,a):
  b+=1
  print(a,"x",b,"=",x)