# -*- coding: utf-8 -*-
"""Código 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13U6NJ6tgqxNVHtPwN6BeoK9CeUxzvwPY

# **SENTENCIAS SELECTIVAS O ESTRUCTURAS DE CONTROL SELECTIVAS.**

Ejemplo 1: Sentencia **`if`**

---
"""

nota = int(input("Dime tu calificación: "))
if nota >= 60:
  print("¡Felicidades aprobaste el examen!")

"""Ejemplo 2: Sentencia **if-else**

---


"""

nota = int(input("Dime tu calificación: "))
if nota >= 60:
  print("¡Felicidades aprobaste el examen!")
else:
  print("¡Ánimo! la próxima vez lo harás mejor")

"""Ejemplo 3: Sentencia **if - elif -else**

---


"""

nota = int(input("Dime tu calificación: "))

if nota >= 80:
  print("¡Felicidades aprobaste el examen!")
elif nota >= 60:
  print("¡Buen trabajo! pero debes esforzarte más")
else:
  print("¡Ánimo! la próxima vez lo harás mejor")

"""Ejemplo 3: Mejorado"""

nota = int(input("Dime tu calificación: "))

if nota < 0 or nota > 100:
  print("¡Dato no válido!, vuelve a correr el programa \ne introduce una calificación entre 0 y 100")
elif nota >= 80:
  print("¡Felicidades aprobaste el examen!")
elif nota >= 60:
  print("¡Buen trabajo! pero debes esforzarte más")
else:
  print("¡Ánimo! la próxima vez lo harás mejor")