# -*- coding: utf-8 -*-
"""Diccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JsbHO2lcUVse3rX1pnFzG4AcUy5Lokyn

# **TEMA 5.- DICCIONARIOS**

Un diccionario es una estructura de datos que permite almacenar cualquier tipo de dato como enteros, cadenas, listas e incluso otros diccionarios. Estos diccionarios nos permiten además identificar cada elemento por una clave (Key).

Sintaxis:
```
Diccionario_Vacío = {}
Diccionario = {'Clave 1': Valor_Clave1, 'Clave 2': Valor_Clave2}
Diccionario_función = dict(Clave 1 = Valor_Clave1, Clave 2 = Valor_Clave2)
```
"""

# Diccionario vacío
Dicc_vacío = {}
print(Dicc_vacío)

# Diccionario
Dicc = {'Nombre' : 'Itzel', 'Apellido Paterno': 'Aranguren', 'Apellido Materno': 'Navarro', 'Edad': 29}
print(Dicc)

#Diccionario por medio de la función dict
Dicc_func = dict(Nombre = 'Itzel', Apellido_Paterno = 'Aranguren', Apellido_Materno = 'Navarro', Edad = 29)
print(Dicc_func)

"""La función **fromkeys()** recibe como parámetros un iterable y un valor, devolviendo un diccionario que contiene como claves los elementos del iterable con el mismo valor ingresado. Si el valor no es ingresado, devolverá un valor none para todas las claves."""

#Sin valor ingresado
Dicc_3 = dict.fromkeys(['a','b','c','d','e'])
print(Dicc_3)

#Con valor ingresado
Dicc_4 = dict.fromkeys(['a','b','c','d','e'],5)
print(Dicc_4)

#Diccionario a partir de un rango
Dicc_5 = dict.fromkeys(range(5),'Hola')
print(Dicc_5)

"""**- ACCESO A LAS CLAVES DE UN DICCIONARIO -**

Para conocer todas las claves que se encuentran en el diccionario se utiliza a la función **keys( )**.
"""

Dicc.keys()

"""**- ACCESO A LOS VALORES DE UN DICCIONARIO -**

Para acceder a los elementos del diccionario, se utilizarán corchetes junto con el identificador clave para obtener su valor **[ 'Clave 1' ]**. Si la clave no está disponible, se marcará un error.
"""

#Dicc = {'Nombre' : 'Itzel', 'Apellido Paterno': 'Aranguren', 'Apellido Materno': 'Navarro', 'Edad': 29}
print('\nNombre:', Dicc['Nombre'])
print('Apellido Paterno:', Dicc['Apellido Paterno'])
print('Apellido Materno:', Dicc['Apellido Materno'])
print('Edad:', Dicc['Edad'])

"""También se puede utilizar a la función **get( )** para acceder al valor de una clave. Si la clave no está disponible, devuelve el valor predeterminado Ninguno (none)."""

print('Nombre:', Dicc.get('Nombre'))
print('Calificaciones:',Dicc.get('Calificaciones'))

"""La función **get( )** a su vez permite definir un caso predeterminado si no se encuentra una clave."""

print('Nombre:', Dicc.get('Nombre',"No se encuentra esa clave"))
print('Calificaciones:',Dicc.get('Calificaciones', "No se encuentra esa clave"))

"""Para conocer todos los valores que contiene un diccionario se utiliza la función **values( )**."""

Dicc.values()

"""El método **setdefault( )** es similar a **get( )**, pero este tiene dos funciones la primera es conocer el valor de una clave y la segunda es agregar una nueva clave y valor a la lista."""

# Conocer el valor de una clave
print("Diccionario original: ", Dicc)
print('Nombre:', Dicc.setdefault('Nombre'))
print('Calificaciones:', Dicc.setdefault('Calificaciones'))
print("Diccionario Final: ", Dicc)

# Agregar una clave y valor al diccionario
print('Diccionario Inicial:', Dicc)
Dicc.setdefault('Año Nacimiento',1990)
print('Diccionario Final:', Dicc)

"""**- AGREGAR ELEMENTOS O ACTUALIZAR UN DICCIONARIO -**

Puede actualizar un diccionario agregando una nueva entrada o un par clave-valor, modificando una entrada existente o eliminando una entrada existente.
"""

# {'Nombre': 'Itzel', 'Apellido Paterno': 'Aranguren', 'Apellido Materno': 'Navarro', 'Edad': 29, 'Calificaciones': None, 'Año Nacimiento': 1990}
Dicc['Nombre'] = 'Arturo' # Actualiza el valor de esa clave
Dicc['Sexo'] = 'Masculino' # Agrega una nueva clave con un valor
print(Dicc)

"""La función **update( )** recibe como parámetro otro diccionario. Si se tienen claves iguales, actualiza el valor de la clave repetida; si no hay claves iguales, este par clave-valor es agregado al diccionario."""

Dicc_1 = dict(a = 1, b = 2, c = 3, d = 4)
Dicc_2 = dict(c = 5, d = 6, e = 7, f = 8)
print('Diccionario Inicial:', Dicc_1)
print('Segundo Diccionario:', Dicc_2)
Dicc_1.update(Dicc_2)
#Dicc_2.update(Dicc_1)
print('Diccionario Final:', Dicc_1)
print('Segundo Diccionario:', Dicc_2)

"""**- ELIMINAR ELEMENTOS DE UN DICCIONARIO -**

La función **del()** permite eliminar elementos individuales del diccionario o borrar todo el diccionario.

"""

#Dicc_1 = dict(a = 1, b = 2, c = 3, d = 4)
#Borrar un elemento del diccionario
print("Diccionario Inicial:", Dicc_1)
del Dicc_1['a']
print("Diccionario Final:", Dicc_1)

#Borrar todo el diccionario
print(Dicc_1)
del Dicc_1

print(Dicc_1)

"""La función **pop( )** recibe como parámetro una clave, la elimina y devuelve su valor. Si no lo encuentra, devuelve error."""

#{'b': 2, 'c': 5, 'd': 6, 'e': 7, 'f': 8}
#print("Diccionario inicial:", Dicc_2)
Dicc_2.pop('f')
#print("Diccionario final:", Dicc_2)

"""La función **clear( )** elimina todos los valores y claves del diccionario dejándolo vacío."""

print("Diccionario inicial:", Dicc_2)
Dicc_2.clear()
print("Diccionario final:", Dicc_2)

"""**- OTRAS FUNCIONES DE DICCIONARIOS -**

La función **copy( )** retorna una copia del diccionario original.
"""

Playera = dict(Playera = 20, Color_Playera = ['Rojo','Azul','Verde'], Tallas_Playera = ['XL','L','M','S','XS'])
Productos = Playera.copy()
print(Productos)

# Acceso a los valores de una lista en un diccionario
print(Playera['Tallas_Playera'][0])

Venta = Playera
print(Venta)

Playera.clear()
print(Venta)
print(Productos)

"""**Función items()**

Permite extraer tanto la clave como el valor en forma de tupla.
"""

Dicc_2 = dict(c = 5, d = 6, e = 7, f = 8)
print("Claves del diccionario: ", Dicc_2.keys())
print("Valores del diccionario: ", Dicc_2.values())
print("Claves y Valores del diccionario: ", Dicc_2.items())
print("Diccionario: ", Dicc_2)

"""La función **zip( )** recibe como parámetros dos elementos iterables, ya sea una cadena, una lista, etcétera. Ambos parámetros deben tener **el mismo número de elementos**. Se devolverá un diccionario relacionando el elemento i-esimo de cada uno de los iterables."""

claves = ['Materia','NRC','Horas Clase', 'Semestre']
valores = ['Programación', 40205, 8, "Segundo Semestre"]
materias = dict(zip(claves, valores))
print(materias)

"""La función **len( )** regresa la cantidad de claves en un diccionario."""

datos = dict(Nombre = 'Arturo', Carrera = 'Ingeniería en computación', Código = 210227232, Semestre = 6, Tel = 33156897)
len(datos)

"""**- ITERAR SOBRE UN DICCIONARIO -**"""

#Iterar sobre un diccionario en las claves y valores
Playera = dict(Cant_Playera = 20, Color_Playera = ['Rojo','Azul','Verde'], Tallas_Playera = ['XL','L','M','S','XS'], Precio = 157.83)
for clave in Playera:
  print(clave,':', Playera[clave]) #Extraemos la clave y su valor

#Iterar sobre un diccionario en las claves y valores con items()
Playera = dict(Cant_Playera = 20, Color_Playera = ['Rojo','Azul','Verde'], Tallas_Playera = ['XL','L','M','S','XS'], Precio = 157.83)
for clave, valor in Playera.items():
  print(clave,':', valor) #Extraemos la clave y su valor

#Iterar sobre un diccionario las claves
Playera = dict(Cant_Playera = 20, Color_Playera = ['Rojo','Azul','Verde'], Tallas_Playera = ['XL','L','M','S','XS'], Precio = 157.83)
for clave in Playera:
  print(clave) #Extraemos la clave

#Iterar sobre un diccionario las claves mediante keys
Playera = dict(Cant_Playera = 20, Color_Playera = ['Rojo','Azul','Verde'], Tallas_Playera = ['XL','L','M','S','XS'], Precio = 157.83)
for clave in Playera.keys():
  print(clave) #Extraemos la clave

#Iterar sobre un diccionario los valores
Playera = dict(Cant_Playera = 20, Color_Playera = ['Rojo','Azul','Verde'], Tallas_Playera = ['XL','L','M','S','XS'], Precio = 157.83)
for clave in Playera:
  print(Playera[clave]) #Extraemos la clave

#Iterar sobre un diccionario los valores mediante values
Playera = dict(Cant_Playera = 20, Color_Playera = ['Rojo','Azul','Verde'], Tallas_Playera = ['XL','L','M','S','XS'], Precio = 157.83)
for valor in Playera.values():
  print(valor) #Extraemos el valor

#Iterar sobre un diccionario con una lista
Playera = dict(Cant_Playera = 20, Color_Playera = ['Rojo','Azul','Verde'], Tallas_Playera = ['XL','L','M','S','XS'], Precio = 157.83)
for valor in Playera['Color_Playera']:
  print(valor)

#Verificar si una clave y un valor pertenecen a un diccionario
x = 21 in Playera.values()
y = "Precio" in Playera

print(x, y)

print("La cantidad de playeras son {} los colores son {} y las tallas son {}".format(Playera["Cant_Playera"], Playera["Color_Playera"],Playera["Tallas_Playera"]) )