# -*- coding: utf-8 -*-
"""Funciones_Parte1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HUC7-p-Des9i0nba8apWLUa_dTj3SiA_

# **TEMA 6: FUNCIONES**

Una **función** es un **bloque de código** reutilizable que se encarga de realizar una determinada tarea.

**- DECLARACIÓN DE UNA FUNCIÓN -**

En Python la función se define mediante la palabra "**def**" seguida del nombre de la función y paréntesis ( ).

Su sintaxis es la siguiente:
```
def nombre_función():
    acciones
```
"""

# Ejemplo de definición de una función

def func():
  print("Esta es mi primer función")

"""Una **función**, no es ejecutada hasta que no sea **invocada** (llamada). Para invocar una función, simplemente se le llama por su nombre."""

# Ejemplo llamado a función
func()

"""Reglas en Python para definir una función:

*   El código dentro de cada función comienza con dos puntos :
*   Las instrucciones que realicé la función deben de estar identadas.
*   La función debe ser declarada antes de utilizarla.

*   Al llamar a una función hay que verificar que el nombre sea el mismo con el que se declaró a esa función.







"""

# Ejemplo 1 declaración de una función de forma incorrecta

def func()
  print ("Esta es mi primer función")

# Ejemplo 2 declaración de una función de forma incorrecta

def func():
print("Esta es mi primer función")

# Ejemplo 3 declaración y llamado de una función de forma incorrecta

funcion()

def funcion():
  print("Esta es mi primer función")

# Ejemplo 4 llamado a función de forma incorrecta

def func(): #Función sin paso de parámetros
  print("Esta es mi primer función")

fnc()

"""**- PARÁMETROS DE UNA FUNCIÓN -**

Un **parámetro** es un valor que la función espera recibir cuando sea llamada (invocada), a fin de ejecutar acciones en base al mismo.
*   Una función puede esperar uno o más parámetros (que irán separados por una coma) o ninguno.
*   Los parámetros se indican entre los paréntesis de la declaración de la función.
"""

# Declaración de una función con 1 parámetro

def cuadrado(num=1):
  print(num**2)

# Declaración de una función con múltiples parámetros

def func_nombre1(Nombre, PrimerAp, SegundoAp):
  print("Nombre completo: ",Nombre, PrimerAp, SegundoAp)

# Declaración de una función con parámetros con valor predeterminado
def func_nombre2(Nombre = 'Juan', PrimerAp = 'Pérez', SegundoAp = 'Sánchez'):
  print("Nombre completo: ", Nombre, PrimerAp, SegundoAp)

"""**- ARGUMENTOS -**

Se le denomina **argumentos** a los valores que se envían en la llamada a función.

"""

# Argumentos en la llamada a función cuadrado

cuadrado()
cuadrado(6)
cuadrado(10)
cuadrado(35)
cuadrado(3)

# Argumentos en la llamada a función func_nombre1

#func_nombre1('Itzel')
func_nombre1('Itzel','Aranguren','Navarro')

# Argumentos en la llamada a función func_nombre2
# def func_nombre2(Nombre = 'Juan', PrimerAp = 'Pérez', SegundoAp = 'Sánchez'):

func_nombre2()
func_nombre2('Navarro', 'Itzel', 'Aranguren')
#func_nombre2(Nombre = 'Itzel', PrimerAp = 'Aranguren', SegundoAp ='Navarro')
func_nombre2(SegundoAp='Navarro', PrimerAp='Aranguren', Nombre='Itzel')

"""**- RETORNO DE DATOS DE UNA FUNCIÓN -**

El comando de **return** en Python especifica qué valor devolver al llamar a una función. Este valor se puede asignar a una variable para su uso posterior.
"""

#Función sin retorno de datos

def cubo(x):
  cubo_num = x**3

#Programa principal

cubo(2)
print(cubo(2))

# Función con retorno de datos

def cubo1(x):
  cubo_num= x**3
  return cubo_num

#cubo1(2)
#print(cubo1(3))

cubo=cubo1(3)
print("El cubo del número 3 es:", cubo)
print(cubo*6)

print(cubo1(8))

#Función Resta
def resta(x, y):
  resultado=x-y
  return (resultado)

#PROGRAMA PRINCIPAL
a = int(input('Ingresa un número: '))
b = int(input('Ingresa otro número: '))
print("Tu resultado de la resta es:", resta(a,b))

"""**Calculadora versión 1 con funciones sin paso de parámetros**


"""

# Calculadora
# Inicio Función Resta
def resta():
  x= int(input('Ingresa un número: '))
  y= int(input('Ingresa otro número: '))
  resultado=x-y
  return (resultado)
# Fin Función Resta

# Inicio Función Suma
def suma():
  x= int(input('Ingresa un número: '))
  y= int(input('Ingresa otro número: '))
  resultado=x+y
  return (resultado)
# Fin Función Suma

# Inicio Función Multiplicación
def mult():
  x = int(input('Ingresa un número: '))
  y = int(input('Ingresa otro número: '))
  resultado = x*y
  return (resultado)
# Fin Función Multiplicación

# Inicio Función División
def div():
  x = int(input('Ingresa un número: '))
  y = int(input('Ingresa otro número: '))
  resultado = x/y
  return (resultado)
# Fin Función División

# PROGRAMA PRINCIPAL

n = 1 #Variable de Control

while n == 1:
  opc=int(input("\nQue operación desea hacer: \n1.Suma \n2.Resta \n3. Multiplicación \n4. División \nSelección: "))
  if opc==1:
    print("\nEl resultado de la suma es:", suma())
  elif opc==2:
    print("\nEl resultado de la resta es:", resta())
  elif opc == 3:
    print("\nEl resultado de la multiplicación es:", mult())
  elif opc == 4:
    print("\nEl resultado de la division es:", div())
  else:
    print("\nDato no válido.")

  n = int(input("\nDesea hacer otra operación: \n1. Si \n2. No \nSelección: "))

print("\nGracias, espero que tenga un buen día.")

# FIN DEL PROGRAMA PRINCIPAL

"""**Calculadora versión 2 con funciones con paso de parámetros**


"""

# Calculadora
# Inicio Función Resta
def Resta(a, b):
  resultado=a-b
  return (resultado)
# Fin Función Resta

# Inicio Función Suma
def Suma(a, b):
  resultado=a+b
  return (resultado)
# Fin Función Suma

# Inicio Función Multiplicación
def Mult(a, b):
  resultado = a*b
  return (resultado)
# Fin Función Multiplicación

# Inicio Función División
def Div(a, b):
  resultado = a/b
  return (resultado)
# Fin Función División

# PROGRAMA PRINCIPAL

n = 1 #Variable de control del while

while n == 1:
  opc=int(input("\nQue operación desea hacer: \n1. Suma \n2. Resta \n3. Multiplicación \n4. División \nSelección: "))
  if opc == 1 or opc == 2 or opc == 3 or opc == 4:
    x = int(input('\nIngresa un número: '))
    y = int(input('Ingresa otro número: '))
  if opc == 1:
    print("\nEl resultado de la suma es:", Suma(x,y))
  elif opc == 2:
    print("\nEl resultado de la resta es:", Resta(x,y))
  elif opc == 3:
    print("\nEl resultado de la multiplicación es:", Mult(x,y))
  elif opc == 4:
    print("\nEl resultado de la division es:", Div(x,y))
  else:
    print("\nDato no válido.")
  n = int(input("\nDesea hacer otra operación: \n1. Si \n2. No \nSelección: "))

print("\nGracias, espero que tenga un buen día.")

# FIN DE PROGRAMA PRINCIPAL

"""**EJERCICIO PRÁCTICO**

Realizar una función con paso de parámetros que a partir de dos números cumpla lo siguiente:

Si el primer número es mayor que el segundo, debe retornar un valor de 1.

Si el primer número es menor que el segundo, debe retornar un valor de -1.

Si ambos números son iguales, debe retornar un valor de 0.
"""

def fun(a,b):
  if a > b:
    return (1)
  elif a < b:
    return (-1)
  else:
    return (0)

#Programa Principal
n1 = float(input("Ingresa un número: "))
n2 = float(input("Ingresa un número: "))
fun(n1,n2)