# -*- coding: utf-8 -*-
"""Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYdcpGe5drJyneOuCl0Qg6iUm4VJrhjr

# **TEMA 3: LISTAS**

Una **lista** es un tipo de dato que contiene una colección de elementos ordenados. Los elementos de una lista no necesitan ser del mismo tipo. Una lista se genera a partir de separar los datos de la lista por una coma y englobarlos entre corchetes.

Sintaxis:

```
Lista = [Dato1, Dato2, ..., DatoN]
```
"""

# Ejemplo de como definir las listas

fruta = ['Pera', 'Manzana', 'Ciruela'] # Lista de palabras (cadenas)
num = [1, 3, 5, 7, 9, 11] # Lista de números enteros
Lista_combinada = ['A','B', 'C', 1, 2, 3]
Lista_vacía = []

print(fruta,'\n',num,'\n',Lista_combinada,'\n',Lista_vacía)

"""**- ACCESO A LOS ELEMENTOS DE LA LISTA -**

Al igual que en los índices del tipo de dato cadena, los índices de la lista comienzan en **0** y se pueden dividir, concatenar, multiplicar, etc. Para acceder a los valores en las listas, se utilizan los corchetes junto con el índice o índices para obtener el valor disponible en ese índice.

Sintaxis:

```
Lista[0]
```
"""

# Ejemplo de acceso mediante los índices de la lista
#fruta = ['Pera', 'Manzana', 'Ciruela'] # Lista de palabras (cadenas)
#num = [1, 3, 5, 7, 9, 11] # Lista de números enteros
#Lista_combinada = ['A','B', 'C', 1, 2, 3]
print(fruta[0]) # Acceso a la posición 0
print(num[1:5]) # Acceso a las posiciones de la 1 a la 4   1 : n-1
print(Lista_combinada[:4]) # Acceso a las posiciones de la lista hasta antes de 4
print(Lista_vacía,'\n') # Se imprimen los valores de la lista

# Ejemplo de acceso al último elemento de la lista

print(fruta[-1]) # El negativo nos indica el valor a la derecha de esa posición
print(num[-2:]) # Extrae los últimos dos elementos de la lista
print(Lista_combinada[-5:-3],'\n')

# Ejemplo de acceso para conocer el índice de un elemento de la lista

print(fruta.index('Manzana')) # La función index devuelve el índice o posición del elemento.
print(num.index(5))

"""Si al buscar un elemento en la lista y este no se encuentra dentro de esa lista Python nos generará un error."""

print(fruta.index('Uva')) # Elemento que no pertenece a la lista

"""Para solventar esto agregamos un código que maneje excepciones."""

# Código que maneja excepciones
try:
  print(fruta.index('Plátano'))
except:
  print('No se encontró ese elemento en la lista')

"""**- CAMBIAR LOS ELEMENTOS DE LA LISTA -**

Para cambiar un elemento de la lista basta con entrar a la posición de ese elemento y asignarle un nuevo valor.
"""

# Ejemplo para cambiar un elemento de la lista

nombres = ['Miguel', 'Vanessa', 'Gustavo']
print('Nombres iniciales: ', nombres)
nombres[0]='Miguel Ángel'
print('Nombres finales:   ', nombres,'\n')

# Ejemplo de cambio múltiple

nombres=['Miguel', 'Vanessa', 'Gustavo']
print('Nombres iniciales: ', nombres)
nombres[0:2]='Miguel Ángel', 'Vanessa Monserrat'
print('Nombres finales:   ', nombres)

"""**- AGREGAR ELEMENTOS A LA LISTA -**

Para agregar elementos a una lista se pueden utilizar 3 diferentes funciones de Python:

*   Función **append**

*   Función **extend**

*   Función **insert**
"""

# Ejemplo función append
# Agrega un solo elemento al final de una lista

letras = ['A','B','C','D','E']
print('Lista inicial: ', letras)
letras.append('F')
print('Lista final:   ', letras)
letras.append('G')
print('Lista final:   ', letras)

# Ejemplo función extend
# Agrega múltiples elementos al final de una lista

letras = ['A','B','C','D','E']
print('Lista inicial: ', letras)
letras.extend(['F','G','H','I','J'])
print('Lista final:   ', letras)
letras.extend(['K','L','M'])
print('Lista final:   ', letras)

# Ejemplo función insert
# Inserta un nuevo elemento en una posición específica de la lista

letras = ['A','B','C','D','E']
print('Lista inicial: ', letras)
letras.insert(1, 'a')
print('Lista final:   ', letras)

"""**- BORRAR ELEMENTOS DE LA LISTA -**

Para eliminar un elemento de la lista, se puede utilizar la instrucción **del** si se conoce qué elemento se quiere eliminar o la función **remove** si no se conoce.

Para eliminar elementos de la lista se pueden utilizar 3 diferentes funciones de Python:

*   Instrucción **del**

*   Función **remove**

*   Función **pop**
"""

# Ejemplo función del
# Elimina uno o varios elementos de la lista a partir de su posición

# Ejemplo 1 borrar un solo elemento de la lista
animales = ['Perro','Gato','Canario','Delfín','Elefante']
print('Lista inicial: ', animales)
del animales[2]
print('Lista final:   ', animales, '\n')

# Ejemplo 2 borrar varios elementos de la lista
animales = ['Perro','Gato','Canario','Delfín','Elefante']
print('Lista inicial: ', animales)
del animales[1:4]
print('Lista final:   ', animales)

# Ejemplo función remove
# Busca un elemento dado en la lista y elimina el primer elemento coincidente

# Ejemplo 1
animales = ['Perro','Gato','Canario','Delfín','Elefante']
print('Lista inicial: ', animales)
animales.remove('Delfín')
print('Lista final:   ', animales, '\n')

# Ejemplo 2
animales = ['Perro','Gato','Canario','Delfín','Gato','Elefante']
print('Lista inicial: ', animales)
animales.remove('Gato')
print('Lista final:   ', animales, '\n')

# Ejemplo función pop
# Elimina y devuelve el elemento borrado de la lista por medio del índice.

# Ejemplo 1
animales = ['Perro','Gato','Canario','Delfín','Elefante']
print('Lista inicial: ', animales)
print('Elemento eliminado: ', animales.pop())
print('Lista final:   ', animales, '\n')

# Ejemplo 2
animales = ['Perro','Gato','Canario','Delfín','Elefante']
print('Lista inicial: ', animales)
print('Elemento eliminado: ', animales.pop(2))
print('Lista final:   ', animales)

# Borrar todos los elementos de una lista
animales=[]
print(animales)

#Cambiar un elemento de la lista forma extendida

nombres = ['Miguel', 'Vanessa', 'Gustavo']
nc = input("Nombre a cambiar: ")
i = nombres.index(nc)
print(nombres)
nc = input("Nuevo Nombre: ")
nombres[i] = nc
print(nombres)

#Cambiar un elemento de la lista forma corta

nombres = ['Miguel', 'Vanessa', 'Gustavo']
i = nombres.index(input("Nombre a cambiar: "))
print(nombres)
nombres[i] = input("Nuevo Nombre: ")
print(nombres)