# -*- coding: utf-8 -*-
"""Practica 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Uj8-jepV4OhrY709NHm_zDzrDRmMR8w
"""

100#Ejercicio 1
a = 8
b = 3.1416
c = 2
d = 5.5

print(a + b)
print(c - d)
print(a * c)
print(b / d)
print(a % d)

#Ejercicio 2
print(a**5)
print(b**5)
print(c**5)
print(d**5)

#Ejercicio 3
R1 = a % b
R2 = b % c
R3 = c % d
R4 = d % c
R5 = c % b
R6 = b % a
print(R1)
print(R2)
print(R3)
print(R4)
print(R5)
print(R6)

#Ejercicio 4
R7 = R1 > R2
R8 = R1 < R2
R9 = R2 == R3
R10 = R2 <= R3
R11 = R3 >= R4
R12 = R3 != R4
R13 = R4 > R5
R14 = R4 < R5
R15 = R5 == R6
R16 = R5 <= R6
R17 = R6 >= R3
R18 = R6 != R3
print(R7)
print(R8)
print(R9)
print(R10)
print(R11)
print(R12)
print(R13)
print(R14)
print(R15)
print(R16)
print(R17)
print(R18)

#Ejercicio 5
R19 = not(R7 and R8 and R9)
R20 = (R10 or R11) and (R12 or not(R13))
R21 = R14 or R15 and R16 or R17 and R18
R22 = not(R19) or not(R20) or not(R21)
print(R19)
print(R20)
print(R21)
print(R22)