# -*- coding: utf-8 -*-
"""Copia de Primer código.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEpVTXCtFcca-t4tKVrtG4Ly2wHErHhF

# ***Esta es una celda de texto. Me permite documentar mi programa.***
"""

# Esta es una celda de código aquí realizaré mi programa.

"""
> **Expresiones**

"""

# Puedo realizar expresiones directamente sin necesidad de asociarlas a una variable.
25*60/3

#Primera expresión de la presentación
9+3*16/2**3-5/2

#Segunda expresión de la presentación
6+2*(7-6)-3*(10+3**2/6)

#Tercera expresión de la presentación
9%5 + (not (5*4%3*7 < 33 or 27/2*3 <= 10*3/10))

# Ejercicio 1 de la presentación
15/3+4*3**2-5*6

# Ejercicio 2 de la presentación
(6*3+8-9/3+2**4)/2

# Ejercicio 3 de la presentación
2+4**2*(6*(1-(7+2)/9))+5

# Ejercicio 4 de la presentación
8 * ((not (7/4>2) or 9>9) and (3>=7/3 or 1+4>=9/2)) + 5

"""

> **Variables**

"""

# Declaración de variables según el tipo de dato primitivo que manejamos

Entero = 150
Real = 14.7856
Complejo = 5.47j
Caracter = 'A'
Cadena = "Hola mundo mi nombre es Itzel"
Logico = True

# Visualizar mis variables en pantalla (Imprimir)

print("Tipo de dato entero: ", Entero)
print("Tipo de dato real: ", Real)
print("Tipo de dato complejo: ", Complejo)
print("Tipo de dato caracter: ", Caracter)
print("Tipo de dato cadena: ", Cadena)
print("Tipo de dato lógico: ", Logico)

# Operaciones con las variables declaradas con anterioridad

print("Tipo de dato entero: ", Entero / 8)
print("Tipo de dato real: ", Real * 3.98)
print("Tipo de dato real: ", Complejo - 9.8j)
print("Tipo de dato caracter: ", Caracter + 'B')
print("Tipo de dato cadena: ", Cadena[3:10]) #Cadena[índice inicial:índice final(índice - 1)]
print("Tipo de dato lógico: ", Logico and False)

"""

> **Cadenas**

"""

# Operaciones con cadenas
# Cadena = "Hola mundo mi nombre es Itzel"
print("Concatenar cadenas: ", Cadena + " BONITO DÍA")
print("Duplicar cadenas: ", Cadena * 2)
print("Extraer una cadena mediante un rango: ", Cadena[1:7])
print("Extraer un caracter de la cadena mediante su índice: ", Cadena[0])