# -*- coding: utf-8 -*-
"""ELIAS ALONSO ZUNIGA OROZCO - Práctica 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hG8gPUg1nKaxND3REwFylphfZ9mDkOAx

### **Práctica 2**

### **Tema:** Sentencias Simples

Realice lo que se solicita en los siguientes ejercicios haciendo sus códigos con sentencias simples (secuencial).

**Nota:** Favor de **NO** usar otras estructuras (if, for, while, etc) para resolver estos ejercicios.

**Ejercicio 1**

> Realice un programa que le solicite al usuario sus datos personales (nombre, domicilio, teléfono y edad) y los imprima en pantalla. **Nota:** Tener en cuenta que datos son de tipo cadena y que datos son numéricos.
"""

N= input("Nombre: ")
D= input("Domicilio: ")
T= input("Teléfono: ")
E= int(input("Edad: "))

print("Sus datos son...")
print("Nombre: ", N)
print("Domicilio: ", D)
print("Teléfono: ", T)
print("Edad: ", E,"años")

"""**Ejercicio 2**


> Realice un programa que le solicite al usuario una cantidad de pesos y los convierta a dólares y euros. Se tomará la equivalencia de 1 Euro = 23.50 pesos y 1 Dólar = 20.56 pesos. Despliegue en pantalla los resultados.


"""

print("Cambio de moneda (Pesos)")
P= float(input("Cantidad de pesos a convertir: "))
D= 20.56
E= 23.50
print(P, "pesos a dolares son: ", D/P)
print(P, "pesos a euros son: ", E/P)

"""**Ejercicio 3**

> Realice un programa que determine cuánto dinero ahorra una persona en un año si considera que cada semana ahorra 15% de su sueldo (considere cuatro semanas por mes y que no cambia el sueldo). Debe de solicitarle al usuario cuanto ganá por semana y desplegar en pantalla el ahorro total que tendrá al año si ahorra el 15% de su salario semanal.


"""

print("Calculadora de ahorro")
Sueldo= float(input("Cantidad de sueldo por semana: "))
Año= Sueldo*48/100*15
Mes= Sueldo*4/100*15
Semana= Sueldo/100*15
print("Si usted ahorra el 15% de su sueldo cada semana tendria...")
print("Cantidad ahorrada por semana: ", Semana, "pesos")
print("Cantidad ahorrada por mes: ", Mes, "pesos")
print("Cantidad ahorrada al año: ", Año, "pesos")

"""**Ejercicio 4**

> Calcule el descuento de un producto, pida al usuario que ingrese el nombre del producto, la cantidad de producto que requiere, el precio por unidad y el porcentaje de descuento. Imprima en pantalla el nombre del producto, la cantidad de producto que lleva, el precio total antes del descuento, y el precio final con descuento.


"""

Producto= input("Nombre del producto: ")
Precio= float(input("Precio del producto: "))
Cantidad= int(input("Cantidad deseada: "))
Descuento= int(input("Porcentaje de descuento: "))
Porcentaje= Precio/100*Descuento
Semitotal= Precio-Porcentaje
Total= Semitotal*Cantidad
print("------------------------")
print(Producto)
print("Precio original: $", Precio)
print("Cantidad repetida del producto: ", Cantidad, "unidades")
print("Precio final: $", Total,"con {:.2F}".format(Descuento), "% de descuento")

"""**Ejercicio 5**

> Realice un algoritmo que le solicite la cantidad de segundos y determine a cuantas horas, minutos y segundos equivale esa cantidad. Ejemplo de salida:



```
Ingrese la cantidad de segundos: 4000

4000 segundos equivalen a 1 hora(s) 6 minuto(s) y 40 segundo(s)
```





"""

Segundos = int(input("Ingrese la cantidad de segundos: "))
A= str(Segundos)
Horas= int(Segundos/3600)
Segundos-= Horas*3600
Minutos= int(Segundos/60)
Segundos-= Minutos*60

print(f"{A} segundos equivalen a {Horas} horas, {Minutos} minutos, {Segundos} segundos")