# -*- coding: utf-8 -*-
"""ELIAS ALONSO ZUNIGA OROZCO - Práctica7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-bpoZsJLOdfmzOk-Ar6YiV_CoxgNKur

### **Práctica 7**

### **Tema:** Listas (Parte II)

De acuerdo a lo visto en el video y código de listas parte II, realice lo que se solicita en los siguientes ejercicios.

**EJERCICIO 1**


> Defina 5 listas distintas (L1, L2, L3, L4, L5), una lista numérica, una lista de letras, una lista de cadenas y dos listas combinadas y realice lo siguiente:
1.   Imprima el número de elementos que contiene cada lista por medio de la función len().
2.   Defina una nueva lista (L6) a partir de la concatenación de L4 + L1 + L3 e imprímala.
3.   Defina una nueva lista (L7) a partir de repetir L2 cuatro veces e imprímala.
4.  Imprima el valor máximo y el mínimo de L5.
5.  Busque si dentro de la lista numérica se encuentra el número 10 e imprima el resultado.
6.  Busque si dentro de la lista de letras se encuentra la letra U e imprima el resultado.
7.  Cuente cuántas veces se repite el valor de algún elemento de la lista L7 e imprima el resultado.
"""

L1, L2, L3, L4, L5 = [1, 2, 3], ['A', 'B', 'C'], ['Fidel', 'Figaro', 'MirryMiau', 'Akane'], [4, 'D', 5], ['E', 6, 'F']
#1
print(len(L1))
print(len(L2))
print(len(L3))
print(len(L4))
print(len(L5))

#2
L6 = L4 + L1 + L3
print(L6)

#3
L7 = L2*4
print(L7)

#4
#print(max(L5))
#print(min(L5))

#5
print(10 in (L1))

#6
print('U' in (L2))

#7
print(L7.count('A'))

"""**EJERCICIO 2**



> Realizar un programa que sume todos los elementos de una lista y despliegue el resultado. (Nota: Utilice a la estructura for para recorrer cada elemento de la lista)

Ejemplo:
```
Lista = [1, 2, 3, 4, 5]
Suma de elementos = 15
```


"""

Lista = [1, 2, 3, 4, 5]
a = 0
for suma in Lista:
  a = suma + a
print('Lista = ', Lista)
print('Suma de elementos = ', a)

"""**EJERCICIO 3**


> Solicite al usuario la cantidad de números enteros a guardar y llene una lista con los elementos otorgados por el usuario. Una vez llenados los datos despliegue la lista original, la lista ordenada, la lista original y la lista ordenada en reversa, el máximo y el mínimo.

**Ejemplo de salida en pantalla:**



```
Ingrese la cantidad de números enteros a guardar: 3

Ingrese el dato 1 = 25
Ingrese el dato 2 = 15
Ingrese el dato 3 = 20

Lista original = [25,15,20]
Lista ordenada = [15,20,25]
Lista original en reversa= [20,15,25]
Lista ordenada en reversa = [25,20,15]
Elemento máximo = 25
Elemento mínimo = 15

```


> **Nota:** Utilice a la estructura for para llenar la lista y recuerde copiar a la lista original mediante la función copy(). Puede utilizar a la función max() y min() para encontrar los elementos con mayor y menor valor.
"""

L = []
N = int(input('Ingrese la cantidad de número enteros a guardar: '))
C = 0

for a in (range(N)):
  C += 1
  D = int(input('Ingrese el dato = '))
  L.append(D)
L2=L.copy()

print('Lista original = ', L)
L.sort()
print('Lista ordenada = ', L)
L2.reverse()
print('Lista original en reversa = ', L2)
L.reverse()
print('Lista ordenada en reversa = ', L)

print('Elemento máximo = ', max(L))
print('Elemento mínimo = ', min(L))

"""**EJERCICIO 4**


> Defina una lista de calificaciones y encuentre la primera, la segunda y la tercera calificación más alta así como las dos calificaciones más bajas. Nota: La lista debe contener elementos repetidos.

**Ejemplo de salida en pantalla:**


```
Calificaciones: [100,86,98,100,98,90,86,85,85,85,83,23,45,84,50]

Primer lugar: 100
Segundo lugar: 98
Tercer lugar: 90
Penúltimo lugar: 45
Último lugar: 23
```

> **Nota:** Utilice a la estructura for para recorrer la lista. Puede utilizar a la función max() y min() para encontrar los elementos con mayor y menor valor.


"""

C = [100, 86, 98, 100, 98, 90, 86, 85, 85, 85, 83, 23, 45, 84, 50]
C2 = C.copy()
C3 = []
for N in C2:
  if N not in C3:
    C3.append(N)
  else:
    C2.remove(N)
C3.sort()
C3.reverse()
print(C3)
print('Primer lugar:', C3[0])
print('Segundo lugar:', C3[1])
print('Tercer lugar:', C3[2])
C3.reverse()
print('Penúltimo lugar:', C3[1])
print('Último lugar:', C3[0])

"""**EJERCICIO 5**



> Definir una lista de números y guardar en una nueva lista todos los elementos que sean menores a 10. A su vez, borrar todos los elementos repetidos y guardarlos en otra lista. Desplegar todas las listas en pantalla.

**Ejemplo de salida en pantalla:**

```
Lista original = [1,1,2,34,5,6,7,8,8,9,10,11,24,0,2]
Lista menores de 10 = [1,1,2,5,6,7,8,8,9,0,2]
Lista sin elementos repetidos = [1,2,34,5,6,7,8,9,10,11,24,0]
```

"""

L = [1, 1, 2, 34, 5, 6, 7, 8, 8, 9, 10, 11, 24, 0, 2]
R = L.copy()
R2 = L.copy()
S = []
M = []

print('Lista original =', L)

for N in L:
  if N <10:
    M.append(N)
print('Lista de menores de 10 = ', M)

for N2 in R2:
  if N2 not in S:
    S.append(N2)
  else:
    R2.remove(N2)
print('Lista sin elementos repetidos = ', S)