# -*- coding: utf-8 -*-
"""ELIAS ALONSO ZUNIGA OROZCO - Práctica_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmZH0QUmq94y1Ws73EGxPPW-0NWcij3e

### **Práctica 4**

### **Tema:** Sentencia Iterativa **while**

Realice lo que se solicita en los siguientes ejercicios haciendo sus códigos con la estructura while.

**Nota:** Favor de **NO** usar a la estructura **for** para resolver estos ejercicios.

**Ejercicio 1**

> Realizar un programa que imprima de forma inversa los números que se encuentran desde el 100 al 1.

Ejemplo de salida en pantalla:


```
Los números del 100 al 1 son:
100
99
98
...
1
```
"""

a=100
while a:
  a=a-1
  print(a+1)

"""**Ejercicio 2**


> Solicitar un número entero y decrementarlo en 2 hasta que el número sea menor que 0, imprimir en
pantalla el número actual.

Ejemplo de salida en pantalla:
```
Ingrese un número: 13
13
11
9
7
5
3
1
```



"""

a=int(input("Ingrese un número: "))
while a>=0:
  print(a)
  a=a-2

"""**Ejercicio 3**


> Solicite un número entero positivo (No se aceptarán números negativos) y calcule su factorial. Recuerde que el factorial de un número natural (entero) se define como el producto de todos los números enteros positivos desde 1. Ejemplo factorial número 5:

> 5! = 1 × 2 × 3 × 4 × 5 = 120

Ejemplo de salida en pantalla:

```
Ingrese el número del cual quiere calcular su factorial: 5
El factorial de 5 es: 120
```




"""

factorial=1
a=int(input("Ingrese un número entero positivo: "))
b=a+0
while a!=0:
  factorial=factorial*a
  a-=1
print("El factorial de", b,"es:", factorial)

"""**Ejercicio 4**


> Algoritmo para la conjetura ULAM de un número. Solicite un número entero positivo (No se aceptarán números negativos). Si es par divídalo
entre 2, si es impar multiplíquelo por 3 y aumente el valor de ese número en 1. Calcular e imprimir los
números enteros positivos repitiendo el proceso hasta llegar a 1.

Ejemplo de salida en pantalla:



```
Ingrese un número: 3

La conjetura ULAM para el número 3 es:
3
10
5
16
8
4
2
1
```




"""

a=int(input("Ingrese un número: "))
b=a+0
print("La conjetura ULAM para el número", a,"es:")
if a%2==0:
  while a>=1:
    a=a/2
    print(int(a*2))
else:
  print(int(a))
  a=a*3+1
  print(int(a))
  a=a/2
  if a%2==0:
    while a>=1:
      a=a/2
      print(int(a*2))
  else:
    print(int(a))
    a=a*3+1
    print(int(a))
    a=a/2
    if a%2==0:
      while a>=1:
        a=a/2
        print(int(a*2))

"""**Ejercicio 5**

> Imprimir los múltiplos de 9 que se encuentran desde 45 hasta 194, calcular el promedio de dichos
múltiplos e imprimir él resultado.

Ejemplo de salida en pantalla:

```
Los múltiplos de 9 que se encuentran desde 45 hasta 194 son:

45
54
63
72
81
90
99
108
117
126
135
144
153
162
171
180
189

La suma de todos los múltiplos es: 1989
El promedio los múltiplos es: 117
```



"""

print("Los múltiplos de 9 que se encuentran desde 45 hasta 194 son:")
a=36
b=0
c=0
while a<=180:
  a=a+9
  print(a)
  b+=a
  c+=1

print("La suma de todos los múltiplos es:", b)
print("El promedio los múltiplos es: ", int(b/c))