# -*- coding: utf-8 -*-
"""ELIAS ALONSO ZUNIGA OROZCO - Práctica 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Lh_RfbulcjB2qR_6hDb14STXn-Gy557

### **Práctica 5**

### **Tema:** Sentencia Iterativa **for**

Realice lo que se solicita en los siguientes ejercicios haciendo sus códigos con la estructura for.

**Nota:** Favor de **NO** usar a la estructura **while** para resolver estos ejercicios.

**Ejercicio 1**


> Solicitar un número entero y decrementarlo en 2 hasta llegar a 1, imprimir en  pantalla el número actual.

**Ejemplo de salida en pantalla:**


```
Ingrese un número entero: 13

La secuencia numérica disminuyendo de 2 en 2 es:
13
11
9
7
5
3
1
```
"""

a=int(input("Ingrese un número entero: "))
print("La secuencia numérica disminuyendo de en 2 es: ")

for x in range(a, 0, -2):
  print(x)

"""**Ejercicio 2**

> Solicitarle al usuario una cadena e imprimir solo a las vocales (considere a mayúsculas y minúsculas):

**Ejemplo de salida en pantalla:**
```
Ingrese una frase: Hola mundo mi nombre es Itzel

Las vocales de la frase son:
o
a
u
o
i
o
e
e
I
e
```


"""

a=input("Ingrese una frase: ")
print("Las vocales de la frase son:")
for x in a:
  if x == "A":
    print("A")
  if x == "E":
    print("E")
  if x == "I":
    print("I")
  if x == "O":
    print("O")
  if x == "U":
    print("U")
  if x == "a":
    print("a")
  if x == "e":
    print("e")
  if x == "i":
    print("i")
  if x == "o":
    print("o")
  if x == "u":
    print("u")

"""**Ejercicio 3**

> Solicitarle al usuario una secuencia de n números por medio de un rango y posteriormente determinar y mostrar en pantalla lo siguiente:

>a) Los múltiplos de 5 y los múltiplos de 3.

>b) La suma de los pares y el producto de los que son múltiplo de 7.  



```
Ingrese el número inicial del rango: 1
Ingrese el número final del rango: 15

En el rango numérico del 1 al 15 se encontró la siguiente información:

El número 2 es par y la suma actual es: 2
El número 3 es múltiplo de 3.
El número 4 es par y la suma actual es: 6
El número 5 es múltiplo de 5.
El número 6 es múltiplo de 3.
El número 6 es par y la suma actual es: 12
El número 7 es múltiplo de 7 y la multiplicación actual es: 7
El número 8 es par y la suma actual es: 20
El número 9 es múltiplo de 3.
El número 10 es múltiplo de 5.
El número 10 es par y la suma actual es: 30
El número 12 es múltiplo de 3.
El número 12 es par y la suma actual es: 42
El número 14 es par y la suma actual es: 56
El número 14 es múltiplo de 7 y la multiplicación actual es: 98
El número 15 es múltiplo de 5.
El número 15 es múltiplo de 3.
```
"""

a = int(input("Ingrese el número inicial del rango: "))
b = int(input("Ingrese el número final del rango: "))
print("En el rango númerico del", a,"al", b,"se encontró la siguiente información: ")
suma=0
c=0
for x in range(a, b+1):
  if x%2==0:
    suma=suma+x
    print("El número", x,"es par y la suma actual es:",suma)
  if x%3==0:
    print("El número", x,"es multiplo de 3")
  if x%5==0:
    print("El número", x,"es multiplo de 5")
  if x%7==0:
    c=7*x
    print("El número", x,"es multiplo de 7 y la multiplicacion actual es:",c)

"""**Ejercicio 4**


> Calcular e imprimir el promedio de los cuadrados de los números comprendidos entre 1 y un número **n** dado.

**Ejemplo de salida en pantalla:**

```
Ingrese un número entero: 4
El cuadrado de 1 es: 1
La suma actual de los cuadrados del 1 al 4 es: 1
El cuadrado de 2 es: 4
La suma actual de los cuadrados del 1 al 4 es: 5
El cuadrado de 3 es: 9
La suma actual de los cuadrados del 1 al 4 es: 14
El cuadrado de 4 es: 16
La suma actual de los cuadrados del 1 al 4 es: 30

El promedio de la suma de los cuadrados del 1 al 4 es: 7.5
```


"""

a = int(input("Ingrese un número entero: "))
b = 0
for x in range(1,a+1):
  print("El cuadrado de", x,"es: ",x*x)
  b+=x*x
  print("La suma actual de los cuadrados del 1 al", a,"es: ", b)

"""

```
# Tiene formato de código
```

**Ejercicio 5**

> Realice un algoritmo que calcule la sucesión de FIBONACCI de un número dado. Recuerde que los dos primeros números de la serie son 0 y 1. El resto se calcula como la suma de los dos números inmediatos que le preceden.

**Ejemplo de salida en pantalla:**


```
Ingrese un número entero: 18

La sucesión de Fibonacci del número 18 es:
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
```


"""

n=int(input("Ingrese un número entero: "))
n=int(n)
print("La sucesión de Fibonacci del número", n,"es:")
a=0
b=1
for x in range(n-1):
  if x==0:
    print("0")
  x=a+b
  b=a
  a=x
  print(x)