# -*- coding: utf-8 -*-
"""ELIAS ALONSO ZUNIGA OROZCO - Práctica 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X2-ljr50vhqQIkmvCVNrJa-5BhEcc63f

### **Práctica 3**

### **Tema:** Sentencias Selectivas

Realice lo que se solicita en los siguientes ejercicios haciendo sus códigos con estructuras selectivas.

**Nota:** Favor de **NO** usar otras estructuras (for, while, etc) para resolver estos ejercicios.

**Ejercicio 1**

> Solicitarle al usuario que ingrese 5 números e imprimir el mayor y el menor de ellos. Ejemplo de salida en pantalla:



```
Introduzca el primer dato: 5
Introduzca el segundo dato: 17
Introduzca el tercer dato: 81
Introduzca el cuarto dato: -15
Introduzca el quinto dato: 50

El número mayor es 81 y el menor -15.
```



**Nota:** **NO** utilizar ninguna función de ordenamiento (min, max, etc.), ni otras estructuras (for, while, etc.), ni tipos de dato ordenados (vectores, matrices, listas, diccionarios, etc.).
"""

#El usuario introduce los datos
a=float(input("Introduzca el primer dato: "))
b=float(input("Introduzca el segundo dato: "))
c=float(input("Introduzca el tercer dato: "))
d=float(input("Introduzca el cuarto dato: "))
e=float(input("Introduzca el quinto dato: "))
#Proceso de numero mayor
if a>=b and a>=c and a>=d and a>=e:
  M=a+0
else:
  if b>=a and b>=c and b>=d and b>=e:
    M=b+0
  else:
    if c>=a and c>=b and c>=d and c>=e:
      M=c+0
    else:
      if d>=a and d>=b and d>=c and d>=e:
        M=d+0
      else:
        if e>=a and e>=b and e>=c and e>=d:
          M=e+0
#Proceso de numero menor
if a<=b and a<=c and a<=d and a<=e:
  m=a+0
else:
  if b<=a and b<=c and b<=d and b<=e:
    m=b+0
  else:
    if c<=a and c<=b and c<=d and c<=e:
      m=c+0
    else:
      if d<=a and d<=b and d<=c and d<=e:
        m=d+0
      else:
        if e<=a and e<=b and e<=c and e<=d:
          m=e+0
#Impresion de resultado
print("El número mayor es",M,"y el menor es",m)

"""**Ejercicio 2**

> Solicite al usuario que ingrese 3 números e imprimirlos en forma ascendente y descendente. Ejemplo de salida en pantalla:


```
Introduzca el primer dato: 9
Introduzca el segundo dato: 2
Introduzca el tercer dato: 16

Los números ingresados en orden ascendente son:
2, 9, 16

Los números ingresados en orden descendente son:
16, 9, 2
```



**Nota:** **NO** utilizar ninguna función de ordenamiento (min, max, etc.), ni otras estructuras (for, while, etc.), ni tipos de dato ordenados (vectores, matrices, listas, diccionarios, etc.).


"""

#Introduccion de datos
a=float(input("Introduzca el primer dato: "))
b=float(input("Introduzca el segundo dato: "))
c=float(input("Introduzca el tercer dato: "))

#Proceso ascendente
if a>b and a>c and b>c:
  print("Los números ingresados en orden ascendente son:\n",c,", ",b,", ",a)
else:
  if a>b and a>c and b<c:
    print("Los números ingresados en orden ascendente son:\n",b,", ",c,", ",a)
  else:
    if a<b and a>c and b>c:
      print("Los números ingresados en orden ascendente son:\n",c,", ",a,", ",b)
    else:
      if a>b and a<c and b<c:
        print("Los números ingresados en orden ascendente son:\n",b,", ",a,", ",c)
      else:
        if a<b and a<c and b>c:
          print("Los números ingresados en orden ascendente son:\n",a,", ",c,", ",b)
        else:
          if a<b and a<c and b<c:
            print("Los números ingresados en orden ascendente son:\n",a,", ",b,", ",c)
#Proceso descendente
if a>b and a>c and b>c:
  print("Los números ingresados en orden descendente son:\n",a,", ",b,", ",c)
else:
  if a>b and a>c and b<c:
    print("Los números ingresados en orden descendente son:\n",a,", ",c,", ",b)
  else:
    if a<b and a>c and b>c:
      print("Los números ingresados en orden descendente son:\n",b,", ",a,", ",c)
    else:
      if a>b and a<c and b<c:
        print("Los números ingresados en orden descendente son:\n",c,", ",a,", ",b)
      else:
        if a<b and a<c and b>c:
          print("Los números ingresados en orden descendente son:\n",b,", ",c,", ",a)
        else:
          if a<b and a<c and b<c:
            print("Los números ingresados en orden descendente son:\n",c,", ",b,", ",a)

"""**Ejercicio 3**

> Solicite un año e imprima si es año bisiesto o no. Recuerde que un año es bisiesto en el calendario Gregoriano, si es divisible entre 4 y no divisible entre 100; también se considera que un año es bisiesto si es divisible entre 400. Ejemplo de salida en pantalla:


```
Introduzca el año: 2020

El año 2020 es bisiesto.
```
"""

#Captura de datos
a=int(input("Introduzca el año: "))
#Proceso e impresion de resultados
if (a%4==0 or a%400==0) and not a%100==0:
  print("El año",a,"es bisiesto")
else:
  print("El año",a,"no es bisiesto")

"""**Ejercicio 4**

> Realice el siguiente menú que le permita al usuario convertir un valor de temperatura:
1. De Celsius ℃ a Farenheit ℉
2. De Celsius ℃ a Kelvin °K
3. De Farenheit ℉ a Celsius ℃
4. De Kelvin °K a Celsius ℃

> Solicite la temperatura e imprima la respectiva conversión. Recuerde que las conversiones se dan de la siguiente forma:

>℃ = (℉ − 32) × 5 / 9

>℉ = (℃ × 9 / 5) + 32

> ℃ = °K − 273.15

> °K = ℃ + 273.15

Ejemplo de salida en pantalla:

```
¡Bienvenido!

  1. De Celsius ℃ a Farenheit ℉
  2. De Celsius ℃ a Kelvin °K
  3. De Farenheit ℉ a Celsius ℃
  4. De Kelvin °K a Celsius ℃

Seleccione una opción: 2

Ingrese la temperatura en grados Celsius: 30

30 grados Celsius equivalen a 303.15 grados Kelvin.

```
"""

#Visual
print("1. Celsius °C a Fahrenheit °F\n2. Celsius °C a Kelvin °K\n3. De Fahrenheit °F a Celsius °C\n4. Kelvin °K a Celsius °C")
#Captura de datos
a=int(input("Seleccione una opción: "))
#Proceso 1
if a==1:
  celsius=int(input("Ingrese la temperatura en grados Celsius: "))
  fahrenheit=9.0/5.0*celsius+32
  print("{} grados Celsius son {} grados Fahrenheit".format(celsius, fahrenheit))
#Proceso 2
if a==2:
  celsius=int(input("Ingrese la temperatura en grados Celsius: "))
  kelvin=celsius+273.15
  print("{} grados Celsius son {} grados Kelvin".format(celsius, kelvin))
#Proceso 3
if a==3:
  fahrenheit=int(input("Ingrese la temperatura en grados Fahrenheit: "))
  celsius=(f-32)*5.0/9.0
  print("{} grados Fahrenheit son {} grados Celsius".format(fahrenheit, celsius))
#Proceso 4
if a==4:
  kelvin=int(input("Ingrese la temperatura en grados Kelvin: "))
  celsius=kelvin-273.15
  print("{} grados Kelvin son {} grados Celsius".format(kelvin, celsius))

"""**Ejercicio 5**

> Leer las horas trabajadas y la paga por hora para calcular el sueldo semanal de un empleado. Cuando las horas de trabajo exceden de 40 se consideran horas extra; las primeras 8 horas extra se pagan al doble; si las horas extra exceden de 8, se pagan las primeras 8 al doble de lo que se pagan las horas normales y el resto al triple de lo que se pagan las horas normales. Imprima las horas trabajadas y el sueldo semanal. Ejemplo de salida en pantalla:

```
Introduzca las horas trabajadas: 56
Introduzca el pago por hora: 35

Su sueldo por 56 horas trabajadas esta semana es de 2800 pesos.
```
"""

#Captura de datos
horas=int(input("Introduzca las horas trabajadas: "))
pago=int(input("Introduzca el pago por hora: "))
#Proceso
if horas>48:
  triples=horas-48
  sueldo=40*pago+(8*pago*2)+(triples*pago*3)
elif horas>40:
  dobles=horas-40
  sueldo=40*pago+(dobles*pago*2)
else:
    sueldo=horas*pago
#Impresion de resultado
print("El sueldo por {} horas trabajadas esta semana es de {} pesos.}".format(horas, sueldo))

"""**Ejercicio 6***

> Leer la fecha de nacimiento (día, mes y año) de una persona y la fecha actual (día, mes y año), para posteriormente imprimir la edad al actual. Ejemplo de salida en pantalla:

```
Introduzca su día de nacimiento: 21
Introduzca su mes de nacimiento: 08
Introduzca el año de nacimiento: 1990

Introduzca el día actual: 23
Introduzca el mes actual: 02
Introduzca el año actual: 2022


Usted tiene 31 años, 6 meses y 2 días.
```
"""

#Se importa datetime para facilitar el trabajo
import datetime
#Captura de datos
dia=int(input("Día de nacimiento: "))
mes=int(input("Mes de nacimiento: "))
año=int(input("Año de nacimiento: "))
#procesos
fecha_de_nacimiento=datetime.datetime(año, mes, dia)
fecha_de_hoy=datetime.datetime.now()
diferenciadias=fecha_de_hoy.day-fecha_de_nacimiento.day
diferenciames=fecha_de_hoy.month-fecha_de_nacimiento.month
diferenciaaño=fecha_de_hoy.year-fecha_de_nacimiento.year
dias_vividos=abs(diferenciadias)
meses=abs(diferenciames)
años=abs(diferenciaaño)
#Impresion de datos
mensaje="Has vivido {} años {} meses {} día(s)".format(años-1,meses, dias_vividos)
print(mensaje)