# -*- coding: utf-8 -*-
"""ELIAS ALONSO ZUNIGA OROZCO - Práctica6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQ414L9-UD7V8Iw5s0-QSayL9DtBCLy_

### **Práctica 6**

### **Tema:** Listas (Parte I)

De acuerdo a lo visto en la primera clase de listas, realice lo que se solicita en los siguientes ejercicios.

**Ejercicio 1**


> Definir una lista que contenga el nombre de su película, serie, videojuego, género musical, canción y  cantante favorito (Lista con 6 elementos) y realice lo siguiente:
1. Imprimir a todos los elementos de la lista.
2. Imprimir solo a los primeros 3 elementos de la lista.
3. Imprimir al último elemento de la lista.
4. Cambiar al cuarto y quinto elemento de la lista e imprimir la nueva lista.
5. Agregar su deporte favorito al final de la lista e imprimir la nueva lista.
6. Agregar su comida, fruta y libro favorito al final de la lista e imprimir la nueva lista.
7. Agregar su color favorito en la posición 5 de la lista e imprimir la nueva lista.
8. Eliminar a los elementos que se encuentran de la posición 0 a 2 e imprimir la nueva lista.
9. Eliminar a su fruta favorita de la lista por medio de la función remove e imprimir la nueva lista.
10. Eliminar a su canción favorita de la lista por medio de la función pop e imprimir la nueva lista.
11. Eliminar a todos los elementos de la lista e imprimir la nueva lista.
"""

lista = ['Wall-E', 'Castelvania', 'Minecraft', 'Hip Hop', 'Cheese Cake', 'Joji']
print(lista)

print(lista[:3])

print(lista[-1])

lista[4:6]='Joji', 'Cheese Cake'
print(lista)

lista.append('Taekwondo')
print(lista)

lista.extend(['Lazaña', 'Mango', 'Oyasumi Punpun'])
print(lista)

lista.insert(5, 'Azul celeste')
print(lista)

del lista[0:3]
print(lista)

lista.remove('Mango')
print(lista)

lista.pop(3)
print(lista)

lista=[]
print(lista)

"""**Ejercicio 2**


> Definir una lista con los elementos de su preferencia (Cualquier cantidad, y cualquier tipo de dato). Una vez definida desplegar la lista en pantalla y  preguntarle al usuario si desea cambiar algún elemento, si la respuesta es afirmativa preguntarle qué  elemento desea cambiar y cuál va a ser su nuevo valor. Desplegar en pantalla la lista actualizada.

**Ejemplo de salida en pantalla:**

```
Esta es la lista:
[“Manzana”, ”Pera”, ”Coco”, “Fresa”, “Mango”, “Durazno”]

¿Desea cambiar un elemento?
1. Si
2. No
Respuesta: 1

Elemento a cambiar: Mango
Nuevo elemento: Uva

Lista actualizada:
[“Manzana”, ”Pera”, ”Coco”, “Fresa”, “Uva”, “Durazno”]


```





"""

lista=["Manzana", "Pera", "Coco", "fresa", "Mango", "Durazno"]
print("Esta es la lista:\n", lista)
Respuesta=input("¿Desea cambiar un elemento?\n1. Si\n2. No\nRespuesta: ")

if Respuesta=="1":
  Elemento=lista.index(input("Elemento a cambiar: "))
  lista[Elemento]=input("Nuevo elemento: ")
  print("Lista actualizada\n", lista)
if Respuesta=="2":
  print("Vuleva pronto")