# -*- coding: utf-8 -*-
"""SECUENCIAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1114BlnQV_P6J8xaH8PW2OtrpJacQObz9

# **SENTENCIAS SIMPLES O ESTRUCTURAS SECUENCIALES**
"""

#Ejemplo 1

n = int(input('Ingrese n: ')) #Sentencia 1 Asignación a variable
m = int(input('Ingrese m: ')) #Sentencia 2 Asignación a variable
suma = n + m #Sentencia 3 Expresión
print ('La suma de n y m es:', suma) #Sentencia 4 Llamada a función

#Ejemplo 2

print("---INICIO---")
a = float(input("Ingresa el primer dato: "))
b = float(input("Ingresa el segundo dato: "))
print("Suma: ", a+b)
print("Resta: ", a-b)
print("Multiplicación: ", a*b)
print("División: ", a/b)
print("---FIN---")

"""En una papelería se venden plumas a **5.50**, cuadernos a **40**, y cajas de colores a **17.85** pesos. Solicitar al usuario la cantidad de plumas, cuadernos y cajas de colores que va a llevar. Hecho esto mostrar en pantalla el monto total de la venta."""

#Versión 1 del código
print("¡Bienvenido a la papelería!")

#Variables de entrada
Prec_pluma = 5.50
Prec_Cuaderno = 40
Prec_Colores = 17.85

#Entrada de datos
Cant_pluma = int(input("Ingresa la cantidad de plumas a llevar: "))
Cant_Cuaderno = int(input("Ingresa la cantidad de cuadernos a llevar: "))
Cant_Colores = int(input("Ingresa la cantidad de colores a llevar: "))

#Procesamiento
Total = Prec_pluma * Cant_pluma + Prec_Cuaderno * Cant_Cuaderno + Prec_Colores * Cant_Colores

#Salida de datos o despliegue en pantalla
print("El precio total de su compra es: ", Total)

#Versión 2 del código
print("¡Bienvenido a la papelería!")

#Variables de entrada
Prec_pluma = 5.50
Prec_Cuaderno = 40
Prec_Colores = 17.85

#Entrada de datos
Cant_pluma = int(input("Ingresa la cantidad de plumas a llevar: "))
Cant_Cuaderno = int(input("Ingresa la cantidad de cuadernos a llevar: "))
Cant_Colores = int(input("Ingresa la cantidad de colores a llevar: "))

#Procesamiento
Tot_Pluma = Prec_pluma * Cant_pluma
Tot_Cuaderno = Prec_Cuaderno * Cant_Cuaderno
Tot_Colores = Prec_Colores * Cant_Colores
Total = Tot_Pluma + Tot_Cuaderno + Tot_Colores

#Salida de datos o despliegue en pantalla
print("El precio total de su compra es: ", Total)

#Versión 3 del código
print("¡Bienvenido a la papelería!")

#Entrada de datos
Cant_pluma = int(input("Ingresa la cantidad de plumas a llevar: "))
Cant_Cuaderno = int(input("Ingresa la cantidad de cuadernos a llevar: "))
Cant_Colores = int(input("Ingresa la cantidad de colores a llevar: "))

#Salida de datos o despliegue en pantalla
print("El precio total de su compra es: ", 5.50 * Cant_pluma + 40 * Cant_Cuaderno + 17.85 * Cant_Colores)

#Versión 4 del código
print("¡Bienvenido a la papelería!")

#Entrada de datos sobreescribiendo variables
Cantidad = int(input("Ingresa la cantidad de plumas a llevar: "))
Total = 5.50 * Cantidad #Variable Acumuladora
Cantidad = int(input("Ingresa la cantidad de cuadernos a llevar: "))
Total = Total + 40 * Cantidad
Cantidad = int(input("Ingresa la cantidad de colores a llevar: "))
Total = Total + 17.85 * Cantidad

#Salida de datos o despliegue en pantalla
print("El precio total de su compra es: ", Total)