# -*- coding: utf-8 -*-
"""Sentencia_Iterativa_For.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aO_mi3fbIxFc-3auNjQQL0K2xOVXD4xb

**Ejemplo 1**

> Algoritmo que recorre las letras de la palabra "Programación" y las imprime.
"""

#Forma 1
for x in "Programación":
  print(x)

#Forma 2 Asignando la cadena a una variable
Frase = "Programación"
for letra in Frase:
  print(letra)

#Forma 3 incremento distinto a 1

Frase = "Programación"
for letra in Frase[::2]: # [] -> Operador de división de cadenas
  print(letra) # [dato inicial : dato final n-1 : incremento o decremento]

#Forma 4 solicitandole al usuario la cadena
Frase = input("Introduzca una frase: ")
for letra in Frase:
  print(letra)

"""**Ejemplo 2**

> Algoritmo que muestra los números del 1 al 20.


"""

for num in range(1,21):#range(inicial, final n-1)
  print(num)

"""**Ejemplo 3**

> Algoritmo que muestra los números del 1 al 20 de forma invertida.


"""

for num in range(20,0,-1): #range(inicial, final n-1, incremento o decremento)
  print(num)

"""**Ejemplo 4**

> Algoritmo que muestra los números del 1 al 50 saltando de 5 en 5.


"""

for num in range(1,51,5):
  print(num)

"""**Ejemplo 5**



> Se le solicita al usuario el dato inicial y final de una secuencia.


"""

x = int(input("Ingrese el número inicial del rango: "))
y = int(input("Ingrese el número final del rango: "))
for num in range(x,y+1):
  print(num)

"""**Ejemplo 6**

> Algoritmo que suma los números que se encuentran del 1 al 15.

"""

suma = 0
for num in range(1,16):
  suma = suma + num
  print("Número: {}\nSuma actual: {}".format(num, suma))
else:
  print("\nLa suma total del 1 al 15 es: ", suma)

# Ejemplo de anidamiento
for i in secuencia:
  if condicion:
    instrucciones
  elif condicion:
    instrucciones
  else:
    instrucciones

for i in secuencia:
  for j in secuencia:
    for x in secuencia:
      while condición:
        instrucciones